[build-system]
requires = ["setuptools",
            "setuptools_scm>=6.2",
            "wheel",
            "oldest-supported-numpy"]
build-backend = 'setuptools.build_meta'

[tool.setuptools_scm]
write_to = "hyperion/_version.py"
