name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      libraries: |
        apt:
          - libhdf5-serial-dev
          - libmpich-dev
        brew:
          - mpich
          - hdf5@1.10
      envs: |
        # Main tests
        - linux: py37-test
        - macos: py38-test
        - linux: py39-test
        - macos: py310-test
        - linux: py311-test
        # Bit-level tests
        - linux: py37-test-bitlevel
          runs-on: ubuntu-20.04
        - linux: py38-test-bitlevel
          runs-on: ubuntu-20.04
        - linux: py39-test-bitlevel
          runs-on: ubuntu-20.04
        - linux: py310-test-bitlevel
          runs-on: ubuntu-20.04
