name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      libraries: |
        apt:
          - libhdf5-serial-dev
          - libmpich-dev
        brew:
          - hdf5-mpi
      envs: |
        # Main tests
        - linux: py39-test
        - macos: py310-test-macos
          runs-on: macos-14
        - linux: py311-test
        - macos: py312-test-macos
          runs-on: macos-14
        # Bit-level tests
        - linux: py39-test-bitlevel
          runs-on: ubuntu-20.04
        - linux: py310-test-bitlevel
          runs-on: ubuntu-20.04
